<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ls</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBwYXRoID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInBhdGgiKTsKU3RyaW5nIGZpbHRlciA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVD
dXJzb3IsICJmaWx0ZXIiKTsKCi8vIHByb2Nlc3MKCkZpbGUgZGlyID0gbmV3IEZpbGUocGF0aCk7
ClN0cmluZ1tdIGZpbGVzOwoKaWYgKGRpci5leGlzdHMoKSkgewoJaWYgKGRpci5pc0RpcmVjdG9y
eSgpKQoJCWZpbGVzID0gZGlyLmxpc3QobmV3IEZpbGVuYW1lRmlsdGVyKCkgewoJCQkKCQkJQE92
ZXJyaWRlCgkJCXB1YmxpYyBib29sZWFuIGFjY2VwdChGaWxlIGZpbGUsIFN0cmluZyBmaWxlbmFt
ZSkgewoJCQkJCgkJCQlyZXR1cm4gIWZpbGVuYW1lLnN0YXJ0c1dpdGgoIi4iKSAmJiAoZmlsdGVy
ID09IG51bGwgfHwgZmlsZW5hbWUuY29udGFpbnMoZmlsdGVyKSk7CgkJCX0KCQl9KTsKCWVsc2UK
CQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigicGF0aCBpcyBub3QgYSBkaXJlY3Rvcnk6IiAr
IHBhdGgpOwp9IGVsc2UgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkRpcmVjdG9yeSBk
b2VzIG5vdCBleGlzdDoiICsgcGF0aCk7Cn0KCi8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1
dChwaXBlbGluZUN1cnNvciwgImZpbGVzIiwgZmlsZXMpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95
KCk7</value>
</Values>
