<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ls</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBwYXRoID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInBhdGgiKTsKU3RyaW5nIGZpbHRlciA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVD
dXJzb3IsICJmaWx0ZXIiKTsKCi8vIHByb2Nlc3MKCkZpbGUgZGlyID0gbmV3IEZpbGUocGF0aCk7
ClN0cmluZ1tdIGZpbGVzOwoKaWYgKGRpci5leGlzdHMoKSkgewoJaWYgKGRpci5pc0RpcmVjdG9y
eSgpKQoJCWZpbGVzID0gZGlyLmxpc3QobmV3IEZpbGVuYW1lRmlsdGVyKCkgewoJCQkKCQkJQE92
ZXJyaWRlCgkJCXB1YmxpYyBib29sZWFuIGFjY2VwdChGaWxlIGZpbGUsIFN0cmluZyBmaWxlbmFt
ZSkgewoJCQkJCgkJCQlyZXR1cm4gIWZpbGVuYW1lLnN0YXJ0c1dpdGgoIi4iKSAmJiAoZmlsdGVy
ID09IG51bGwgfHwgZmlsZW5hbWUuY29udGFpbnMoZmlsdGVyLnRvTG93ZXJDYXNlKCkpKTsKCQkJ
fQoJCX0pOwoJZWxzZQoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJwYXRoIGlzIG5vdCBh
IGRpcmVjdG9yeToiICsgcGF0aCk7Cn0gZWxzZSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bigiRGlyZWN0b3J5IGRvZXMgbm90IGV4aXN0OiIgKyBwYXRoKTsKfQoKLy8gcGlwZWxpbmUgb3V0
CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiZmlsZXMiLCBmaWxlcyk7CnBpcGVsaW5l
Q3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
