<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFileWithFilter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBmbmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJmbmFtZSIpOwpTdHJpbmdbXSBmaWx0ZXJzID0gSURhdGFVdGlsLmdldFN0cmluZ0FycmF5
KHBpcGVsaW5lQ3Vyc29yLCAiZmlsdGVycyIpOwpTdHJpbmcgbWF4TGluZXMgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAibWF4TGluZXMiKTsKCi8vIHByb2Nlc3MKCmludCBt
YXggPSAtMTsKCnRyeSB7bWF4ID0gSW50ZWdlci5wYXJzZUludChtYXhMaW5lcyk7fSBjYXRjaCAo
RXhjZXB0aW9uIGUpIHt9CgpTdHJpbmdbXSBtYXRjaGVkTGluZXMgPSByZWFkRmlsZUFzU3RyaW5n
TGlzdChmbmFtZSwgZmlsdGVycywgbWF4KTsKCi8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1
dChwaXBlbGluZUN1cnNvciwgIm1hdGNoZWRMaW5lcyIsIG1hdGNoZWRMaW5lcyk7CklEYXRhVXRp
bC5wdXQocGlwZWxpbmVDdXJzb3IsICJtYXRjaGVkQ291bnQiLCAiIiArIG1hdGNoZWRMaW5lcy5s
ZW5ndGgpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgoJ</value>
</Values>
