<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sanitize</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyB2YWx1ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJ2YWx1ZSIpOwpTdHJpbmcgZGVmYXVsdFZhbHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhw
aXBlbGluZUN1cnNvciwgImRlZmF1bHRWYWx1ZSIpOwpTdHJpbmcgbWF4TGVuID0gSURhdGFVdGls
LmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgIm1heExlbiIpOwoJCQovLyBwcm9jZXNzIAoKaW50
IG1heCA9IDA7CgkJCnRyeSB7IG1heCA9IEludGVnZXIucGFyc2VJbnQobWF4TGVuKTsgfSBjYXRj
aChFeGNlcHRpb24gZSkge30gLy8gZG8gbm93J3QKCQkKaWYgKHZhbHVlID09IG51bGwpIAoJdmFs
dWUgPSBkZWZhdWx0VmFsdWU7CgppZiAodmFsdWUgIT0gbnVsbCkgewoJCgl2YWx1ZSA9IHZhbHVl
LnJlcGxhY2VBbGwoIlsgX1xcLlxcQFxcIVxcJVxcJFxcI1xcXlxcJlxcKlxcKFxcKV0iLCItIik7
Cn0KCi8vIHBpcGVsaW5lIG91dAoJCQpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAidmFs
dWUiLCB2YWx1ZS50b0xvd2VyQ2FzZSgpKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoJ</value>
</Values>
