<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractCNFromResult</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKSURhdGEgcmVzdWx0cyA9IElEYXRhVXRpbC5nZXRJRGF0YShwaXBlbGluZUN1cnNv
ciwgInJlc3VsdHMiKTsKClN0cmluZyBjblZhbHVlID0gbnVsbDsKSURhdGEgY25PYmplY3QgPSBu
dWxsOwoKaWYgKHJlc3VsdHMgIT0gbnVsbCkKewoJSURhdGFDdXJzb3IgcmVzdWx0c0N1cnNvciA9
IHJlc3VsdHMuZ2V0Q3Vyc29yKCk7CglyZXN1bHRzQ3Vyc29yLm5leHQoKTsKCVN0cmluZyBrZXkg
PSByZXN1bHRzQ3Vyc29yLmdldEtleSgpOwoJCglpZiAoa2V5ICE9IG51bGwpCgl7CgkJY25PYmpl
Y3QgPSAoSURhdGEpIHJlc3VsdHNDdXJzb3IuZ2V0VmFsdWUoKTsKCQljblZhbHVlID0ga2V5LnN1
YnN0cmluZyhrZXkuaW5kZXhPZigiPSIpKzEpOwoJfQoJCglyZXN1bHRzQ3Vyc29yLmRlc3Ryb3ko
KTsKfQoKLy8gcGlwZWxpbmUgb3V0CklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJjbiIs
IGNuVmFsdWUpOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiY25PYmplY3QiLCBjbk9i
amVjdCk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
