<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copy</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBzcmNEaXJlY3RvcnkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgInNyY0RpciIpOwpTdHJpbmcgc3JjID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJzcmNOYW1lIik7ClN0cmluZyB0Z3REaXJlY3RvcnkgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInRndERpciIpOwpTdHJpbmcgdGd0ID0gSURh
dGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJ0Z3ROYW1lIik7ClN0cmluZyBvdmVy
d3JpdGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29yLCAib3ZlcndyaXRlIik7
CgpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgovLyBwcm9jZXNzCgp0cnkgewoJCglpZiAoIW5l
dyBGaWxlKHRndERpcmVjdG9yeSkuZXhpc3RzKCkpOwoJCW5ldyBGaWxlKHRndERpcmVjdG9yeSku
bWtkaXJzKCk7CgkJCglpZiAodGd0ID09IG51bGwpCgkJdGd0ID0gc3JjOwoJCglpZiAgKG5ldyBG
aWxlKHNyY0RpcmVjdG9yeSwgc3JjKS5pc0RpcmVjdG9yeSgpKSB7CgkJbmV3IERpckNvcGllcihG
aWxlU3lzdGVtcy5nZXREZWZhdWx0KCkuZ2V0UGF0aChzcmNEaXJlY3RvcnksIHNyYyksIEZpbGVT
eXN0ZW1zLmdldERlZmF1bHQoKS5nZXRQYXRoKHRndERpcmVjdG9yeSwgdGd0KSkuY29weShvdmVy
d3JpdGUgIT0gbnVsbCAmJiBvdmVyd3JpdGUuZXF1YWxzSWdub3JlQ2FzZSgidHJ1ZSIpKTsKCX0g
ZWxzZSBpZiAob3ZlcndyaXRlICE9IG51bGwgJiYgb3ZlcndyaXRlLmVxdWFsc0lnbm9yZUNhc2Uo
InRydWUiKSkgewoJCUZpbGVzLmNvcHkoRmlsZVN5c3RlbXMuZ2V0RGVmYXVsdCgpLmdldFBhdGgo
c3JjRGlyZWN0b3J5LCBzcmMpLCBGaWxlU3lzdGVtcy5nZXREZWZhdWx0KCkuZ2V0UGF0aCh0Z3RE
aXJlY3RvcnksIHRndCksIFN0YW5kYXJkQ29weU9wdGlvbi5SRVBMQUNFX0VYSVNUSU5HKTsKCX0g
ZWxzZSB7CgkJdHJ5IHsKCQkJRmlsZXMuY29weShGaWxlU3lzdGVtcy5nZXREZWZhdWx0KCkuZ2V0
UGF0aChzcmNEaXJlY3RvcnksIHNyYyksIEZpbGVTeXN0ZW1zLmdldERlZmF1bHQoKS5nZXRQYXRo
KHRndERpcmVjdG9yeSwgdGd0KSk7CgkJfSBjYXRjaCAoRmlsZUFscmVhZHlFeGlzdHNFeGNlcHRp
b24gZSkgewoJCQlTZXJ2ZXJBUEkubG9nRXJyb3IoZSk7CgkJfQoJfQp9IGNhdGNoIChJT0V4Y2Vw
dGlvbiBlKSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQoKLy8gcGlwZWxpbmUg
b3V0CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAidGd0UGF0aCIsIG5ldyBGaWxlKHRn
dERpcmVjdG9yeSwgdGd0KS5nZXRQYXRoKCkpOw==</value>
</Values>
