<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">dateTimeRangeForDayDate</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CkRhdGUgZGF0ZSA9IChEYXRlKSBJRGF0YVV0aWwuZ2V0KHBpcGVsaW5lQ3Vyc29y
LCAiZGF0ZSIpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgpEYXRlIHN0YXJ0ID0gbnVsbDsK
RGF0ZSBlbmQgPSBudWxsOwoKaWYgKGRhdGUgPT0gbnVsbCkKCWRhdGUgPSBuZXcgRGF0ZSgpOwoK
c3RhcnQgPSBnZXRTdGFydE9mRGF5KGRhdGUpOwplbmQgPSBnZXRFbmRPZkRheShkYXRlKTsKCi8v
IHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImRhdGVUaW1lQXRT
dGFydE9mRGF0ZSIsIHN0YXJ0KTsKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImRhdGVU
aW1lQXRFbmRPZkRhdGUiLCBlbmQpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
