<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeMimeBodyToFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBwYXRoID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInBhdGgiKTsKSURhdGEgZGF0YSA9IElEYXRhVXRpbC5nZXRJRGF0YShwaXBlbGluZUN1cnNv
ciwgImRhdGEiKTsKU3RyaW5nIGV4dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJleHQiKTsKCklEYXRhQ3Vyc29yIGRhdGFDdXJzb3IgPSBkYXRhLmdldEN1cnNvcigpOwpT
dHJpbmcgc3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhkYXRhQ3Vyc29yLCAic3RyaW5nIik7
CmJ5dGVbXSBieXRlcyA9IChieXRlW10pIElEYXRhVXRpbC5nZXQoZGF0YUN1cnNvciwgImJ5dGVz
Iik7CklucHV0U3RyZWFtIHN0cmVhbSA9IChJbnB1dFN0cmVhbSkgSURhdGFVdGlsLmdldChkYXRh
Q3Vyc29yLCAic3RyZWFtIik7CgpkYXRhQ3Vyc29yLmRlc3Ryb3koKTsKCi8vIHByb2Nlc3MKCmlm
IChzdHJpbmcgIT0gbnVsbCkKCXN0cmVhbSA9IG5ldyBCeXRlQXJyYXlJbnB1dFN0cmVhbShzdHJp
bmcuZ2V0Qnl0ZXMoKSk7CmVsc2UgaWYgKGJ5dGVzICE9IG51bGwpCglzdHJlYW0gPSBuZXcgQnl0
ZUFycmF5SW5wdXRTdHJlYW0oYnl0ZXMpOwoKTWltZUNvbnRlbnRSZWFkZXIgbWYgPSBuZXcgTWlt
ZUNvbnRlbnRSZWFkZXIocGF0aCwgc3RyZWFtLCBleHQpOwoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0
YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiZmlsZW5hbWUiLCBtZi5sYXN0UmVhZEZpbGUpOwpw
aXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
