<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractArgsFromPipeline</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBleGNsdWRlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJleGNsdWRlIiApOwoKLy8gcHJvY2VzcwoKSURhdGEgYXJncyA9IElEYXRhRmFjdG9y
eS5jcmVhdGUoKTsKSURhdGFDdXJzb3IgYyA9IGFyZ3MuZ2V0Q3Vyc29yKCk7CgpwaXBlbGluZUN1
cnNvci5ob21lKCk7Cgp3aGlsZShwaXBlbGluZUN1cnNvci5oYXNNb3JlRGF0YSgpKQp7CglTdHJp
bmcga2V5ID0gcGlwZWxpbmVDdXJzb3IuZ2V0S2V5KCk7CglPYmplY3QgdmFsdWUgPSBwaXBlbGlu
ZUN1cnNvci5nZXRWYWx1ZSgpOwoJCglpZiAodmFsdWUgaW5zdGFuY2VvZiBTdHJpbmcgJiYgIWtl
eS5lcXVhbHMoImV4Y2x1ZGUiKSAmJiAoZXhjbHVkZSA9PSBudWxsIHx8ICFrZXkuc3RhcnRzV2l0
aChleGNsdWRlKSkpCgkJSURhdGFVdGlsLnB1dChjLCBrZXksIHZhbHVlKTsKCQoJcGlwZWxpbmVD
dXJzb3IubmV4dCgpOwp9CmMuZGVzdHJveSgpOwoKLy8gcGlwZWxpbmUgb3V0CklEYXRhVXRpbC5w
dXQocGlwZWxpbmVDdXJzb3IsICJhcmdzIiwgYXJncyk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3ko
KTs=</value>
</Values>
