<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readPropertiesFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGZpbGVuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAiZmlsZW5hbWUiKTsKCi8vIHBy
b2Nlc3MKClN0cmluZ1tdIHByb3BzID0gcmVhZEZpbGVBc1N0cmluZ0xpc3QoZmlsZW5hbWUsIG51
bGwsIC0xKTsKQXJyYXlMaXN0PElEYXRhPiBvdXQgPSBuZXcgQXJyYXlMaXN0PElEYXRhPigpOwoK
Zm9yIChTdHJpbmcgcCA6IHByb3BzKSB7CgkKCWlmIChwLmluZGV4T2YoIj0iKSAhPSAtMSkgewoJ
CQoJCWludCBpID0gcC5pbmRleE9mKCI9Iik7CgkJU3RyaW5nIGsgPSBwLnN1YnN0cmluZygwLCBp
KTsKCQlTdHJpbmcgdiA9IHAuc3Vic3RyaW5nKGkrMSk7CgkJCgkJSURhdGEgbyA9IElEYXRhRmFj
dG9yeS5jcmVhdGUoKTsKCQlJRGF0YUN1cnNvciBvYyA9IG8uZ2V0Q3Vyc29yKCk7CgkJCQkJCQoJ
CUlEYXRhVXRpbC5wdXQob2MsICJrZXkiLCBrKTsKCQlJRGF0YVV0aWwucHV0KG9jLCAidmFsdWUi
LCB2KTsKCQlvYy5kZXN0cm95KCk7CgkJCgkJb3V0LmFkZChvKTsKCX0KfQoKLy8gcGlwZWxpbmUg
b3V0CgpJRGF0YVV0aWwucHV0KGMsICJwcm9wZXJ0aWVzIiwgb3V0LnRvQXJyYXkobmV3IElEYXRh
W291dC5zaXplKCldKSk7CmMuZGVzdHJveSgpOw==</value>
</Values>
