<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readPropertiesFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKU3Ry
aW5nIGZpbGVuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyhjLCAiZmlsZW5hbWUiKTsKCi8vIHBy
b2Nlc3MKClN0cmluZ1tdIHByb3BzID0gcmVhZEZpbGVBc1N0cmluZ0xpc3QoZmlsZW5hbWUpOwpB
cnJheUxpc3Q8SURhdGE+IG91dCA9IG5ldyBBcnJheUxpc3Q8SURhdGE+KCk7Cgpmb3IgKFN0cmlu
ZyBwIDogcHJvcHMpIHsKCQoJaWYgKHAuaW5kZXhPZigiPSIpICE9IC0xKSB7CgkJCgkJaW50IGkg
PSBwLmluZGV4T2YoIj0iKTsKCQlTdHJpbmcgayA9IHAuc3Vic3RyaW5nKDAsIGkpOwoJCVN0cmlu
ZyB2ID0gcC5zdWJzdHJpbmcoaSsxKTsKCQkKCQlJRGF0YSBvID0gSURhdGFGYWN0b3J5LmNyZWF0
ZSgpOwoJCUlEYXRhQ3Vyc29yIG9jID0gby5nZXRDdXJzb3IoKTsKCQkJCQkJCgkJSURhdGFVdGls
LnB1dChvYywgImtleSIsIGspOwoJCUlEYXRhVXRpbC5wdXQob2MsICJ2YWx1ZSIsIHYpOwoJCW9j
LmRlc3Ryb3koKTsKCQkKCQlvdXQuYWRkKG8pOwoJfQp9CgovLyBwaXBlbGluZSBvdXQKCklEYXRh
VXRpbC5wdXQoYywgInByb3BlcnRpZXMiLCBvdXQudG9BcnJheShuZXcgSURhdGFbb3V0LnNpemUo
KV0pKTsKYy5kZXN0cm95KCk7</value>
</Values>
