<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeDuplicates</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CklEYXRhW10gZG9jSW4gPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShwaXBlbGlu
ZUN1cnNvciwgImRvY0xpc3RJbiIpOwpTdHJpbmcgc2VhcmNoS2V5ID0gSURhdGFVdGlsLmdldFN0
cmluZyhwaXBlbGluZUN1cnNvciwgImtleSIpOwoKLy8gcHJvY2VzcwoJCQkKTGlzdDxPYmplY3Q+
IGRvY091dCA9IG51bGw7CgppZiAoZG9jSW4gIT0gbnVsbCkgewkJCQkJCglBcnJheUxpc3Q8U3Ry
aW5nPiBwcm9jZXNzZWRLZXlzID0gbmV3IEFycmF5TGlzdDxTdHJpbmc+KCk7Cglkb2NPdXQgPSBu
ZXcgQXJyYXlMaXN0PE9iamVjdD4oKTsKCQoJZm9yIChJRGF0YSBkb2MgOiBkb2NJbikgewoJCQoJ
CUlEYXRhIG5vdER1cGVkRG9jID0gY2hlY2tGb3JEdXBsaWNhdGVzKGRvYywgc2VhcmNoS2V5LCBw
cm9jZXNzZWRLZXlzKTsKCQkKCQlpZiAobm90RHVwZWREb2MgIT0gbnVsbCkKCQkJZG9jT3V0LmFk
ZChub3REdXBlZERvYyk7Cgl9Cn0KCQkKLy8gcGlwZWxpbmUgb3V0CgkKaWYgKGRvY091dCAhPSBu
dWxsKQoJSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImRvY0xpc3RPdXQiLCBkb2NPdXQu
dG9BcnJheShuZXcgSURhdGFbZG9jT3V0LnNpemUoKV0pKTsKCnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTs=</value>
</Values>
