<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zipit</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBzb3VyY2VGb2xkZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVs
aW5lQ3Vyc29yLCAic291cmNlRm9sZGVyIik7ClN0cmluZyB6aXBGaWxlID0gSURhdGFVdGlsLmdl
dFN0cmluZyhwaXBlbGluZUN1cnNvciwgInppcEZpbGUiKTsKCQkKLy8gcHJvY2VzcwoJCQpTeXN0
ZW0ub3V0LnByaW50bG4oImJ1aWxkIGRpciBpcyAiICsgc291cmNlRm9sZGVyICsgIiwgcHJlcGFy
aW5nIHppcCBmaWxlICIgKyB6aXBGaWxlKTsKCQkKdHJ5IHsKCWlmICghemlwRmlsZS5zdGFydHNX
aXRoKCIvIikgJiYgIXppcEZpbGUuc3RhcnRzV2l0aCgiLi8iKSkKCQl6aXBGaWxlID0gbmV3IEZp
bGUobmV3IEZpbGUoc291cmNlRm9sZGVyKS5nZXRQYXJlbnQoKSwgemlwRmlsZSkuZ2V0QWJzb2x1
dGVQYXRoKCk7CgkJCglpZiAoIXppcEZpbGUuZW5kc1dpdGgoIi56aXAiKSkKCQl6aXBGaWxlICs9
ICIuemlwIjsKCQkKCW5ldyBaaXBwZXIoKS56aXBJdChzb3VyY2VGb2xkZXIsIHppcEZpbGUpOwoJ
CQoJYnl0ZVtdIGNvbnRlbnRzOwoJCQoJY29udGVudHMgPSBGaWxlcy5yZWFkQWxsQnl0ZXMoRmls
ZVN5c3RlbXMuZ2V0RGVmYXVsdCgpLmdldFBhdGgoemlwRmlsZSkpOwp9IGNhdGNoIChJT0V4Y2Vw
dGlvbiBlKSB7CgllLnByaW50U3RhY2tUcmFjZSgpOwoJCQkKCXRocm93IG5ldyBTZXJ2aWNlRXhj
ZXB0aW9uKCJDYW5ub3QgcmVhZCB6aXBwZWQgZmlsZSAnIiArIHppcEZpbGUgKyAiJyAiICsgZS5n
ZXRMb2NhbGl6ZWRNZXNzYWdlKCkpOwp9CgkJCi8vIHBpcGVsaW5lIG91dAoJCQovL0lEYXRhVXRp
bC5wdXQocGlwZWxpbmVDdXJzb3IsICJjb250ZW50cyIsIGNvbnRlbnRzKTsKCQkKaWYgKHppcEZp
bGUgIT0gbnVsbCkKCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJ6aXBGaWxlIiwgbmV3
IEZpbGUoemlwRmlsZSkuZ2V0TmFtZSgpKTsKCQkKCXBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTs=
</value>
</Values>
