<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addDocsWithPatternToList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKSURhdGFbXQlpbkxpc3QgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShwaXBlbGlu
ZUN1cnNvciwgImluTGlzdCIpOwpTdHJpbmcJcGF0dGVybiA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZWxpbmVDdXJzb3IsICJwYXR0ZXJuIik7CgovLyBwcm9jZXNzIAoKTGlzdDxJRGF0YT4gb3V0
TGlzdCA9IG5ldyBBcnJheUxpc3Q8SURhdGE+KCk7CgppZiAoaW5MaXN0ICE9IG51bGwpCnsKCWZv
ciAoSURhdGEgZCA6IGluTGlzdCkKCQlvdXRMaXN0LmFkZChkKTsKfQoKd2hpbGUgKHBpcGVsaW5l
Q3Vyc29yLmhhc01vcmVEYXRhKCkpCnsKCXBpcGVsaW5lQ3Vyc29yLm5leHQoKTsKCVN0cmluZyBr
ZXkgPSBwaXBlbGluZUN1cnNvci5nZXRLZXkoKTsKCU9iamVjdCB2YWx1ZSA9IHBpcGVsaW5lQ3Vy
c29yLmdldFZhbHVlKCk7CgkKCWlmIChrZXkuY29udGFpbnMocGF0dGVybikgJiYgdmFsdWUgaW5z
dGFuY2VvZiBJRGF0YSkKCQlvdXRMaXN0LmFkZCgoSURhdGEpIHZhbHVlKTsKfQoKLy8gcGlwZWxp
bmUgb3V0CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAib3V0TGlzdCIsIG91dExpc3Qu
dG9BcnJheShuZXcgSURhdGFbb3V0TGlzdC5zaXplKCldKSk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTs=</value>
</Values>
