<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addDocsWithPatternToList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lIGluCgpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOwpJRGF0YVtdCWluTGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KHBpcGVs
aW5lQ3Vyc29yLCAiaW5MaXN0Iik7ClN0cmluZwlwYXR0ZXJuID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhwaXBlbGluZUN1cnNvciwgInBhdHRlcm4iKTsKCi8vIHByb2Nlc3MgCgpMaXN0PElEYXRhPiBv
dXRMaXN0ID0gbmV3IEFycmF5TGlzdDxJRGF0YT4oKTsKCmlmIChpbkxpc3QgIT0gbnVsbCkKewoJ
Zm9yIChJRGF0YSBkIDogaW5MaXN0KQoJCW91dExpc3QuYWRkKGQpOwp9Cgp3aGlsZSAocGlwZWxp
bmVDdXJzb3IuaGFzTW9yZURhdGEoKSkKewoJcGlwZWxpbmVDdXJzb3IubmV4dCgpOwoJU3RyaW5n
IGtleSA9IHBpcGVsaW5lQ3Vyc29yLmdldEtleSgpOwoJT2JqZWN0IHZhbHVlID0gcGlwZWxpbmVD
dXJzb3IuZ2V0VmFsdWUoKTsKCQoJaWYgKGtleS5jb250YWlucyhwYXR0ZXJuKSAmJiB2YWx1ZSBp
bnN0YW5jZW9mIElEYXRhKQoJCW91dExpc3QuYWRkKChJRGF0YSkgdmFsdWUpOwp9CgovLyBwaXBl
bGluZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJvdXRMaXN0Iiwgb3V0TGlz
dC50b0FycmF5KG5ldyBJRGF0YVtvdXRMaXN0LnNpemUoKV0pKTsKcGlwZWxpbmVDdXJzb3IuZGVz
dHJveSgpOw==</value>
</Values>
