<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFileReference</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKU3RyaW5nIHBhdGggPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29y
LCAicGF0aCIpOwpTdHJpbmcgZiA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3Is
ICJmaWxlIik7CgovLyBwcm9jZXNzCgpGaWxlIGZpbGU7CgppZiAocGF0aCAhPSBudWxsKQoJZmls
ZSA9IG5ldyBGaWxlKHBhdGgsIGYpOwplbHNlCglmaWxlID0gbmV3IEZpbGUoZik7CgppZiAoIWZp
bGUuZXhpc3RzKCkpCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRmlsZSAnIiArIChwYXRo
ICE9IG51bGwgPyBwYXRoICsgIi8iICsgZmlsZSA6IGZpbGUpICsgIicgZG9lcyBub3QgZXhpc3Qh
Iik7CgovLyBwaXBlbGluZSBvdXQKCklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJmaWxl
IiwgZmlsZSk7CklEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJzaW1wbGVOYW1lIiwgZmls
ZS5nZXROYW1lKCkpOwpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAicGF0aCIsIGZpbGUu
Z2V0UGFyZW50RmlsZSgpLmdldEFic29sdXRlUGF0aCgpKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJv
eSgpOwoKCQ==</value>
</Values>
