<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFileReference</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lIGluCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBwYXRoID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInBhdGgiKTsKU3RyaW5nIGYgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVsaW5lQ3Vyc29y
LCAiZmlsZSIpOwoKLy8gcHJvY2VzcwoKRmlsZSBmaWxlOwoKaWYgKHBhdGggIT0gbnVsbCkKCWZp
bGUgPSBuZXcgRmlsZShwYXRoLCBmKTsKZWxzZQoJZmlsZSA9IG5ldyBGaWxlKGYpOwoKaWYgKCFm
aWxlLmV4aXN0cygpKQoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkZpbGUgJyIgKyAocGF0
aCAhPSBudWxsID8gcGF0aCArICIvIiArIGZpbGUgOiBmaWxlKSArICInIGRvZXMgbm90IGV4aXN0
ISIpOwoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiZmls
ZSIsIGZpbGUpOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgoJ</value>
</Values>
