<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">incrementDate</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CkRhdGUgZGF0ZSA9IChEYXRlKSBJRGF0YVV0aWwuZ2V0KHBpcGVsaW5lQ3Vyc29y
LCAiZGF0ZSIpOwpTdHJpbmcgZGF5cyA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJz
b3IsICJkYXlzIik7ClN0cmluZyBob3VycyA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVD
dXJzb3IsICJob3VycyIpOwpTdHJpbmcgbWludXRlcyA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlw
ZWxpbmVDdXJzb3IsICJtaW51dGVzIik7ClN0cmluZyBzZWNvbmRzID0gSURhdGFVdGlsLmdldFN0
cmluZyhwaXBlbGluZUN1cnNvciwgInNlY29uZHMiKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
OwoKLy8gcHJvY2VzcwoKaW50IGhvdXJzSW50ID0gMDsKaW50IG1pbnNJbnQgPSAwOwppbnQgc2Vj
c0ludCA9IDA7Cgp0cnkgeyBob3Vyc0ludCA9IEludGVnZXIucGFyc2VJbnQoZGF5cykgKiAyNDt9
IGNhdGNoKEV4Y2VwdGlvbiBlKXt9CnRyeSB7IGhvdXJzSW50ICs9IEludGVnZXIucGFyc2VJbnQo
aG91cnMpO30gY2F0Y2goRXhjZXB0aW9uIGUpe30KdHJ5IHsgbWluc0ludCA9IEludGVnZXIucGFy
c2VJbnQobWludXRlcyk7fSBjYXRjaChFeGNlcHRpb24gZSl7fQp0cnkgeyBzZWNzSW50ID0gSW50
ZWdlci5wYXJzZUludChzZWNvbmRzKTt9IGNhdGNoKEV4Y2VwdGlvbiBlKXt9CgppZiAoZGF0ZSA9
PSBudWxsKQoJZGF0ZSA9IG5ldyBEYXRlKCk7CgpkYXRlID0gRGF0ZVRpbWVVdGlscy5zdW1UaW1l
VG9EYXRlKGRhdGUsIGhvdXJzSW50LCBtaW5zSW50LCBzZWNzSW50KTsKCi8vIHBpcGVsaW5lIG91
dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImRhdGUiLCBkYXRlKTsKcGlwZWxpbmVD
dXJzb3IuZGVzdHJveSgpOw==</value>
</Values>
