<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getGlobalVariable</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKCklEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpT
dHJpbmcga2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJrZXkiKTsKU3RyaW5nIHZh
bHVlID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJkZWZhdWx0VmFsdWUiKTsKU3RyaW5n
IGlnbm9yZUVycm9yID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJpZ25vcmVFcnJvcnMi
KTsKCi8vIHByb2Nlc3MKClN0cmluZyBpc1NlY3VyZSA9ICJmYWxzZSI7Cgp0cnkgewogICAgR2xv
YmFsVmFyaWFibGVzTWFuYWdlciBtYW5hZ2VyID0gR2xvYmFsVmFyaWFibGVzTWFuYWdlci5nZXRJ
bnN0YW5jZSgpOwogICAgR2xvYmFsVmFyaWFibGVzLkdsb2JhbFZhcmlhYmxlVmFsdWUgZ3ZWYWx1
ZSA9IG1hbmFnZXIuZ2V0R2xvYmFsVmFyaWFibGVWYWx1ZShrZXkpOwogICAgCiAgICB2YWx1ZSA9
IGd2VmFsdWUuZ2V0VmFsdWUoKTsKICAgIGlzU2VjdXJlID0gIiIgKyBndlZhbHVlLmlzU2VjdXJl
KCk7Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CglpZiAodmFsdWUgPT0gbnVsbCAmJiAoaWdub3Jl
RXJyb3IgPT0gbnVsbCB8fCBpZ25vcmVFcnJvciA9PSAiZmFsc2UiKSkKCQl0aHJvdyBuZXcgU2Vy
dmljZUV4Y2VwdGlvbihlKTsKfQoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KGN1cnNv
ciwgInZhbHVlIiwgdmFsdWUpOwpJRGF0YVV0aWwucHV0KGN1cnNvciwgImlzU2VjdXJlIiwgaXNT
ZWN1cmUpOwoJCmN1cnNvci5kZXN0cm95KCk7</value>
</Values>
