<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">untar</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgdGFyZmlsZSA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoYywgInRhcmZpbGUiKTsKU3RyaW5nIGRlc3REaXIgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKGMsICJkZXN0RGlyIik7CgpGaWxlIGRlc3REaXJmID0gbmV3IEZpbGUoZGVz
dERpcik7CgppZiAoIWRlc3REaXJmLmV4aXN0cygpKSB7CglkZXN0RGlyZi5ta2RpcnMoKTsKfSBl
bHNlIGlmICghZGVzdERpcmYuaXNEaXJlY3RvcnkoKSkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oIkludmFsaWQgZGVzdGluYXRpb24sIG5vdCBhIGRpcmVjdG9yeSEiKTsKfQoKdHJ5IHsK
CWlmICh0YXJmaWxlLmVuZHNXaXRoKCIuZ3oiKSkgewoJCWRlY29tcHJlc3NHelRhcihuZXcgRmls
ZSh0YXJmaWxlKSwgZGVzdERpcmYpOwoKCX0gZWxzZSB7CgkJZGVjb21wcmVzc1RhcihuZXcgRmls
ZSh0YXJmaWxlKSwgZGVzdERpcmYpOwoJfQp9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7Cgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQoKYy5kZXN0cm95KCk7</value>
</Values>
