<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgZm5hbWUgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGMsICJmbmFtZSIpOwpTdHJpbmcgbG9hZGFzID0gSURhdGFVdGlsLmdl
dFN0cmluZyhjLCAibG9hZEFzIik7ClN0cmluZyBpZ25vcmVFcnJvciA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoYywgImlnbm9yZUVycm9yIik7CgppZiAoZm5hbWUgPT0gbnVsbCkKCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKCJwcm92aWRlIGZpbGUgbmFtZSBwbGVhc2UiKTsKCi8vIHByb2Nlc3MK
CmJ5dGVbXSBkYXRhID0gbnVsbDsKSW5wdXRTdHJlYW0gaW4gPSBudWxsOwoKdHJ5IHsKCWlmIChs
b2FkYXMgIT0gbnVsbCAmJiBsb2FkYXMuZXF1YWxzSWdub3JlQ2FzZSgic3RyZWFtIikpCgkJaW4g
PSBuZXcgRmlsZUlucHV0U3RyZWFtKG5ldyBGaWxlKGZuYW1lKSk7CgllbHNlCgkJZGF0YSA9IEZp
bGVzLnJlYWRBbGxCeXRlcyhQYXRocy5nZXQoZm5hbWUpKTsKfSBjYXRjaCAoTm9TdWNoRmlsZUV4
Y2VwdGlvbiBlICkgewoJaWYgKGlnbm9yZUVycm9yID09IG51bGwgfHwgIWlnbm9yZUVycm9yLmVx
dWFsc0lnbm9yZUNhc2UoInRydWUiKSkKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsK
fSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgewoJCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihl
KTsKfQoKLy8gcGlwZWxpbmUgb3V0CgppZiAoZGF0YSAhPSBudWxsKSB7CgkKCWlmIChsb2FkYXMg
IT0gbnVsbCAmJiBsb2FkYXMuZXF1YWxzSWdub3JlQ2FzZSgic3RyaW5nIikpCgkJSURhdGFVdGls
LnB1dChjLCAic3RyaW5nIiwgbmV3IFN0cmluZyhkYXRhKSk7CgllbHNlCgkJSURhdGFVdGlsLnB1
dChjLCAiYnl0ZXMiLCBkYXRhKTsKCWMuZGVzdHJveSgpOwp9IGVsc2UgewoJSURhdGFVdGlsLnB1
dChjLCAic3RyZWFtIiwgaW4pOwp9</value>
</Values>
