<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createFolder</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgZm5hbWUgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGMsICJuYW1lIik7ClN0cmluZyBmb3JjZSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoYywgImZvcmNlIik7CgpGaWxlIGRpciA9IG5ldyBGaWxlKGZuYW1lKTsKU3RyaW5nIHN1
Y2Nlc3MgPSAiZXhpc3RzIjsKbG9uZyBzaW5jZSA9IDA7CmJvb2xlYW4gaXNFbXB0eSA9IHRydWU7
CgppZiAoIWRpci5leGlzdHMoKSkKewoJaWYgKGRpci5ta2RpcnMoKSkKCQlzdWNjZXNzID0gImRv
bmUiOwoJZWxzZQoJCXN1Y2Nlc3MgPSAiZmFpbGVkIjsKfSBlbHNlIGlmIChmb3JjZSAhPSBudWxs
ICYmIGZvcmNlLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkgewoJCglkZWxldGVEaXIoZGlyKTsK
CQoJaWYgKGRpci5ta2RpcnMoKSkKCQlzdWNjZXNzID0gImRvbmUiOwoJZWxzZQoJCXN1Y2Nlc3Mg
PSAiZmFpbGVkIjsKfSBlbHNlIHsKCglzaW5jZSA9IChuZXcgRGF0ZSgpLmdldFRpbWUoKSAgLSBu
ZXcgRGF0ZShkaXIubGFzdE1vZGlmaWVkKCkpLmdldFRpbWUoKSkgLyA2MDAwMDsKCWlzRW1wdHkg
PSBkaXIubGlzdCgpLmxlbmd0aCA9PSAwOwp9CgovLyBwaXBlbGluZSBvdXQKCklEYXRhVXRpbC5w
dXQoYywgInN1Y2Nlc3MiLCBzdWNjZXNzKTsKCmlmIChzdWNjZXNzLmVxdWFscygiZXhpc3RzIikp
IHsKCUlEYXRhVXRpbC5wdXQoYywgInNpbmNlIiwgIiIgKyBzaW5jZSk7CglJRGF0YVV0aWwucHV0
KGMsICJpc0VtcHR5IiwgIiIgKyBpc0VtcHR5KTsKfQpjLmRlc3Ryb3koKTsKCQ==</value>
</Values>
