<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getNextUniqueCode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgY29kZSA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoYywgImNvZGUiKTsKU3RyaW5nIG51bURpZ2l0cyA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoYywgIm51bURpZ2l0cyIpOwpTdHJpbmcgcHJlZml4ID0gSURhdGFVdGlsLmdldFN0
cmluZyhjLCAicHJlZml4Iik7ClN0cmluZyBudW1lcmljID0gSURhdGFVdGlsLmdldFN0cmluZyhj
LCAibnVtZXJpYyIpOwoKU3RyaW5nIG5leHRDb2RlOwoKaWYgKG51bWVyaWMgIT0gbnVsbCAmJiBu
dW1lcmljLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkKCW5leHRDb2RlID0gcm90YXRlTnVtcyhj
b2RlLCBudW1EaWdpdHMgIT0gbnVsbCA/IEludGVnZXIucGFyc2VJbnQobnVtRGlnaXRzKSA6IDUp
OwplbHNlCgluZXh0Q29kZSA9IHJvdGF0ZUNoYXJzKGNvZGUsIG51bURpZ2l0cyAhPSBudWxsID8g
SW50ZWdlci5wYXJzZUludChudW1EaWdpdHMpIDogNSk7CgppZiAocHJlZml4ICE9IG51bGwpCglu
ZXh0Q29kZSA9IHByZWZpeCArIG5leHRDb2RlOwoKSURhdGFVdGlsLnB1dChjLCAiY29kZSIsIG5l
eHRDb2RlKTsKCmMuZGVzdHJveSgpOw==</value>
</Values>
