<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getNextUniqueCode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgY29kZSA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoYywgImNvZGUiKTsKU3RyaW5nIG51bURpZ2l0cyA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoYywgIm51bURpZ2l0cyIpOwpTdHJpbmcgcHJlZml4ID0gSURhdGFVdGlsLmdldFN0
cmluZyhjLCAicHJlZml4Iik7ClN0cmluZyBudW1lcmljID0gSURhdGFVdGlsLmdldFN0cmluZyhj
LCAibnVtZXJpYyIpOwoKU3RyaW5nIG5leHRDb2RlOwoKaWYgKG51bWVyaWMgIT0gbnVsbCAmJiBu
dW1lcmljLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkKCW5leHRDb2RlID0gcm90YXRlTnVtcyhw
cmVmaXgsIGNvZGUsIG51bURpZ2l0cyAhPSBudWxsID8gSW50ZWdlci5wYXJzZUludChudW1EaWdp
dHMpIDogNSk7CmVsc2UKCW5leHRDb2RlID0gcm90YXRlQ2hhcnMocHJlZml4LCBjb2RlLCBudW1E
aWdpdHMgIT0gbnVsbCA/IEludGVnZXIucGFyc2VJbnQobnVtRGlnaXRzKSA6IDUpOwoKaWYgKHBy
ZWZpeCAhPSBudWxsKQoJbmV4dENvZGUgPSBwcmVmaXggKyBuZXh0Q29kZTsKCklEYXRhVXRpbC5w
dXQoYywgImNvZGUiLCBuZXh0Q29kZSk7CgpjLmRlc3Ryb3koKTs=</value>
</Values>
