<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getNextUniqueCode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgbnVtRGlnaXRzID0g
SURhdGFVdGlsLmdldFN0cmluZyhjLCAibnVtRGlnaXRzIik7ClN0cmluZyBwcmVmaXggPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGMsICJwcmVmaXgiKTsKU3RyaW5nIG51bWVyaWMgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKGMsICJudW1lcmljIik7CgpTdHJpbmcgbmV4dENvZGU7CgppZiAobnVtZXJpYyAh
PSBudWxsICYmIG51bWVyaWMuZXF1YWxzSWdub3JlQ2FzZSgidHJ1ZSIpKQoJbmV4dENvZGUgPSBy
b3RhdGVOdW1zKG51bURpZ2l0cyAhPSBudWxsID8gSW50ZWdlci5wYXJzZUludChudW1EaWdpdHMp
IDogNSk7CmVsc2UKCW5leHRDb2RlID0gcm90YXRlQ2hhcnMobnVtRGlnaXRzICE9IG51bGwgPyBJ
bnRlZ2VyLnBhcnNlSW50KG51bURpZ2l0cykgOiA1KTsKCmlmIChwcmVmaXggIT0gbnVsbCkKCW5l
eHRDb2RlID0gcHJlZml4ICsgbmV4dENvZGU7CgpJRGF0YVV0aWwucHV0KGMsICJjb2RlIiwgbmV4
dENvZGUpOwoKYy5kZXN0cm95KCk7</value>
</Values>
