<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertChildElementsToDocList</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YSBkb2MgPSBJRGF0YVV0
aWwuZ2V0SURhdGEoYywgImRvYyIpOwpTdHJpbmcgZG9jS2V5ID0gSURhdGFVdGlsLmdldFN0cmlu
ZyhjLCAibmFtZUZvckRvY1JlZiIpOwoKLy8gcHJvY2VzcwoKTGlzdDxJRGF0YT4gb3V0ID0gbmV3
IEFycmF5TGlzdDxJRGF0YT4oKTsKCmlmIChkb2MgIT0gbnVsbCkgewoJSURhdGFDdXJzb3IgZGMg
PSBkb2MuZ2V0Q3Vyc29yKCk7CgkKCWRjLmZpcnN0KCk7CgkKCQoJZG8gewoJCVN0cmluZyBrZXkg
PSBkYy5nZXRLZXkoKTsKCQlJRGF0YSB2YWx1ZSA9IChJRGF0YSkgZGMuZ2V0VmFsdWUoKTsKCQkK
CQlpZiAoZG9jS2V5ICE9IG51bGwpIHsKCQkJSURhdGFDdXJzb3IgdmMgPSB2YWx1ZS5nZXRDdXJz
b3IoKTsKCQkJSURhdGFVdGlsLnB1dCh2YywgZG9jS2V5LCBrZXkpOwoJCQl2Yy5kZXN0cm95KCk7
CgkJfQoJCQoJCW91dC5hZGQoKElEYXRhKSB2YWx1ZSk7Cgl9IHdoaWxlIChkYy5uZXh0KCkpOwp9
CgovLyBvdXRwdXQKCklEYXRhVXRpbC5wdXQoYywgImRvY0xpc3QiLCBvdXQudG9BcnJheShuZXcg
SURhdGFbb3V0LnNpemUoKV0pKTsKYy5kZXN0cm95KCk7Cgk=</value>
</Values>
